apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    name: simple-webapp-mysql-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      name: simple-webapp-mysql
  template:
    metadata:
      labels:
        name: simple-webapp-mysql
    spec:
      containers:
      - name: webapp
        image: kodekloud/simple-webapp-mysql
        # image: kodekloud/flask-session-app:1 # to test VPA with script load.sh
        ports:
        - protocol: TCP
          containerPort: 8080
        resources:
          limits:
            memory: "200Mi"
            cpu: 2
          requests:
            memory: "20Mi"
            cpu: 1
        envFrom:
        - secretRef:
            name: app-secret