apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simple-web-app-hpa
  namespace: test
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp-deployment
  targetCPUUtilizationPercentage: 60