#! in a real project, do not push this file to git, because it contains sensitive information
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: test
type: Opaque
data:
  DB_Host: c3FsMDE=  #sql01
  DB_User: cm9vdA==  #root
  DB_Password: cGFzc3dvcmQxMjM= #password123
