kind: Service
apiVersion: v1
metadata:
  name: webapp-service
  namespace: test
spec:
  selector:
    name: simple-webapp-mysql
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31031
