apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-traffic
  namespace: default
spec:
  podSelector: {} # empty selector matches all pods in the namespace
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {} # allow all incoming traffic
  egress:
    - {} # allow all outgoing traffic
