apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  # These IP should match with the Ips in your kind cluster
  # In this case, the ip of masterplane, worker1, worker2 is: 192.168.97.2, 192.168.97.3, 192.168.97.4
  addresses:
  - 192.168.97.10-192.168.97.20
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool