apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-localhost-access
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 192.168.50.224/32 # replace with your localhost IP