kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
- role: control-plane
  kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      apiServer:
        certSANs:
        - "172.1.2.1" # <-- REPLACE with your host IP
        - "localhost"
        - "127.0.0.1"        
  extraPortMappings:
    - containerPort: 6443
      hostPort: 6443
      listenAddress: "0.0.0.0"
      protocol: TCP
- role: worker
  labels:
    tier: kindWorker1
- role: worker
  labels:
    tier: kindWorker2
- role: worker
  labels:
    tier: kindWorker3
networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "0.0.0.0"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  kubeProxyMode: "ipvs"