apiVersion: v1
kind: Service
metadata:
  name: webapp-color-svc
spec:
  type: NodePort
  selector:
    app: fe
  ports:
    - port: 8080        # Port exposed within the cluster
      targetPort: 8080  # Port on the pods to forward traffic to
      nodePort: 30080   # Port exposed on the nodes (optional, Kubernetes will assign one if not specified)
      protocol: TCP