apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        # ports:
        # - containerPort: 80
        env:
        - name: NGINX_PORT
          value: "8080"
        resources:
          limits:
            memory: "1Gi"
            cpu: 1
          requests:
            memory: "128Mi"
            cpu: "0.25"
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: app-config